---
title: TU Delft PhD Thesis Template
format:
  tudelft-pdf:
    keep-tex: true
  tudelft-html: default
author:
  - name: Patrick Altmeyer
    affiliations:
      - name: Delft University of Technology
        department: EEMCS
        id: 1
    email: p.altmeyer@tudelft.nl
    url: https://www.patalt.org/
abstract: |
  This document is a template demonstrating the `thesis-tudelft` format.
toc: true

defense-date: "Tuesday 20, June 2025 at 10:00 o'clock"
author-degree: MSc Research, University of Research, Country
author-birthplace: "Amsterdam, The Netherlands"
committee:
  - title: "Prof. dr. A. Kleiner"
    affiliation: "Delft University of Technology"
    role: "promotor"
  - title: "Dr. A.A. Aaronson"
    affiliation: "Delft University of Technology"
    role: "copromotor"
  - title: "Prof. dr. ir. A.B.C.D. van de Lange-Achternaam"
    name-too-long: true
    affiliation: "Delft University of Technology"
independent-members:
  - title: "Prof. dr. A. Jansen"
    affiliation: "Delft University of Technology"
  - title: "Prof. dr. ir. A.B.C.D. van de Andere Lange-Achternaam"
    name-too-long: true
    affiliation: "Delft University of Technology"
  - title: "Prof. dr. N. Nescio"
    affiliation: "Politecnico di Milano, Italy"
  - title: "Prof. dr. ir. J. Doe"
    affiliation: "Delft University of Technology"
    role: "reserve member"
other-members:
  - title: "Prof. dr. ir. J. de Wit"
    affiliation: "Delft University of Technology"
  - title: "Dr. ir. Q. de Zwart"
    affiliation: "Delft University of Technology"
keywords: 
  - Quarto
  - Extension
  - Template
institute-message: "This is an optional message to acknowledge partner institutes."
institute-logos:
  - path: "www/delft-final.png"
dedication:
  - text: "They not like us."
    author: Kendrik Lamar
---

# Preface {.unnumbered}

# Summary {.unnumbered}

# Samenvatting {.unnumbered}

\pagebreak
\mainmatter

# Introduction

This is a Quarto extension for generating your TU Delft PhD Thesis in Quarto.

# Cool Quarto Things

## Custom Callouts 

<!-- TODO: Adapt when possible -->

The template adds custom numbered blocks using the embedded [ute/custom-numbered-blocks](https://github.com/ute/custom-numbered-blocks) extension, which supports HTML and PDF with non-standard cross-references (i.e. `\ref{}` syntax). We provide two custom numbered blocks:

We provide two custom numbered blocks:

1. **TRQ** for Thesis Research Questions
2. **RQ** for Research Questions
3. **Rec** for Recommendations

TRQ \ref{trq:what} is an example of a Thesis Research Question; RQ \ref{rq:what} is an example of a Research Questions; Rec. \ref{rec:what} is an example of a recommendation. 

::: {.TRQ #trq:what}

## What is a TRQ?

This is a Thesis Research Question, that you might want to use in the introduction of your thesis.

:::

::: {.RQ #rq:what}

## What is a RQ?

This is a Research Question, that you might want to use in any chapter of your thesis.

:::

::: {.Rec #rec:what}

## What is a Rec?

This is a Recommendation that you might want to use in the conclusion of your thesis.

:::
